name: Sync Code to B Repo  

on:  
  workflow_dispatch:  

jobs:  
  sync-code:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout A Repo  
        uses: actions/checkout@v3  
        with:  
          ref: develop  

      - name: Add B Repo as Remote  
        run: |  
          pwd
          GITLAB_A_REPO="https://github.com/sherminMing/lnp-history.git"  
          GITLAB_A_BRANCH="develop"  

          GITLAB_B_REPO="https://github.com/sherminMing/lnp-history-backup.git"  
          GITLAB_B_BRANCH="develop"  
  
          LOCAL_REPO_DIR=$PROJECT_DIR/temp

          if [ -d "$LOCAL_REPO_DIR" ]; then  
              rm -rf "$LOCAL_REPO_DIR"  
          fi  
  
          git clone --single-branch -b "$GITLAB_A_BRANCH" "$GITLAB_A_REPO" "$LOCAL_REPO_DIR"  
            
          cd "$LOCAL_REPO_DIR"
            
          git remote add gitlab_b "$GITLAB_B_REPO"  
          
          git pull origin main
           
          git push -u gitlab_b "$GITLAB_A_BRANCH:$GITLAB_B_BRANCH"    --force --verbose
             
          pwd
          
          echo "Code from  GitLab A  $GITLAB_A_BRANCH  GitLab B  $GITLAB_B_BRANCH branch."



