name: Sync A to B

on:
  push:
    branches:
      - develop

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout A develop
        uses: actions/checkout@v2
        with:
          ref: main
          repository: sherminMing/Lnp-history
      - name: Push to B develop
        uses: ad-m/github-push-action@master
        with:
          branch: main
          repository: sherminMing/lnp-history-backup
          github_token: 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
