name: Create PR
on:
  workflow_dispatch:

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Automated PR created by GitHub Action
          title: Automated Pull Request
          body: |
            This is an automated pull request created by a GitHub Action.
            Please review and merge as necessary.
          branch: release/07/08
