name: Create PR
on:
  workflow_dispatch:

jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release/07/08
      - name: Reset promotion branch
        run: |
          git fetch origin main:release/07/08
          git reset --hard main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: release/07/08
