name: Create PR
on:
  workflow_dispatch:

jobs:  
  create-pull-request:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v3  
        with:  
          ref: feature/new-feature  
  
      - name: Create Pull Request  
        uses: peter-evans/create-pull-request@v6  
        with:  
          token: ${{ secrets.GITHUB_TOKEN }}  
          commit-message: Update for new feature  
          title: 'New Feature Update'  
          body: |  
            This PR updates the code with the new feature.  
            branch: release/07/09
          base: main  
          labels: |  
            automerge  
