name: Create PR
on:
  workflow_dispatch:

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add file
        run: |
            ls
            touch example.txt
            echo "Hello, world!" >> example.txt
            cat example.txt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Automated PR created by GitHub Action
          title: Automated Pull Request
          body: |
            This is an automated pull request created by a GitHub Action.
            Please review and merge as necessary.
          branch: release
