name: Job approver test

on:
  workflow_dispatch:

jobs:
  update-version:
    name: job1
    runs-on: [ ubuntu-latest ]
    environment: stage
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: version-artifact

      - name: Read Version from File
        id: versionNumber
        run: |
          ls 
