name: Sync Code to B Repo  
  
on:  
  workflow_dispatch:
  
jobs:  
  sync-code:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout A Repo  
        uses: actions/checkout@v3  
        with:  
          ref: develop  
  
      - name: Clone B Repo  
        run: |  
          git clone "https://${{ secrets.B_REPO_ACCESS_TOKEN }}@github.com/sherminMing/lnp-history-backup.git"  
          cd lnp-history-backup  
          git config user.name "sherminMing"  
          git config user.email "1837236006@qq.com"  
  
      - name: Push to B Repo  
        run: |  
          cd  lnp-history-backup
          git remote set-url origin "https://${{ secrets.B_REPO_ACCESS_TOKEN }}@github.com/sherminMing/lnp-history-backup.git"  
          git fetch origin  
          git checkout develop  
          git reset --hard origin/develop      
          git add .  
          git commit -m "Sync from A's develop to B's develop"  
          git push origin develop  
  
      - name: Clean Up  
        if: always()  
        run: |  
          rm -rf lnp-history-backup
