name: Sync Repository

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Sync Repository
      uses: Andre601/repository-sync
      env:
        PAT: ${{ secrets.PAT }}
        EMAIL: ${{ secrets.EMAIL }}
        USER: sherminMing
        OWNER: sherminMing
        REPO: lnp-history-backup
