name: Merge to main

on:
  workflow_dispatch:

jobs:  
  merge-to-main:
    name: Merge code to main
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout  Code
        uses: actions/checkout@v2  
        with:  
          fetch-depth: 0
          
      - name: Megre to main
        run: |
           git config --global user.email "automationNoReply@ssnc.com"
           git config --global user.name "Github Automation"  
           git checkout main  
           git pull  
           git merge --no-ff origin/$GITHUB_REF  
           git push origin main  
