name: Merge to main

on:
  workflow_dispatch:
  
jobs:
  merge-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge release branch to main
        run: |
            SOURCE_BRANCH="release"
            TARGET_BRANCH="main"
            git checkout $TARGET_BRANCH
            git pull origin $TARGET_BRANCH
            git merge $SOURCE_BRANCH --no-ff
            git push origin $TARGET_BRANCH
