name: Merge to main

on:
  workflow_dispatch:
  
jobs:
  merge-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge release branch to main
        run: |
          BRANCH_TO_MERGE="release/07/09"
          git checkout --track origin/main
          git pull origin main
          git merge $BRANCH_TO_MERGE
        
          if [ $? -eq 0 ]; then
              git push origin main
          else
              echo "A merger conflict occurs, manually resolve the conflict and submit it again."
          fi
