name: Job approver test

on:
  workflow_dispatch:

jobs:  
  merge-to-main:
    name: Merge to main
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout  Code
        uses: actions/checkout@v2  
        with:  
          fetch-depth: 0
          
      - name: Megre to main
        run: |
           ls    
